### ISSUE TITLE
Validating required|integer is turning into float|int|numeric-string

### ISSUE THREAD

**Issue by Firehed** [jbboehr/phpstan-laravel-validation#2]
Hi - thanks for putting this together! It's helping me out a lot with typechecking Laravel validation results :)

I noticed that the following validation appears to be producing the wrong type:

```php

        $valid = $request->validate([
            'amount' => 'required|integer',
        ])->validated();
        \PHPStan\dumpType($valid); //  array{amount: float|int|numeric-string}
```

Unless Laravel's `integer` validation is doing something really odd, it seems like the result of this should instead be `int|numeric-string`, without the `float` in the union.

I'm currently using `dev-master 1fe0f3b` of this extension.

**Comment by jbboehr** [comment]
Yeah definitely looks like a problem: https://github.com/jbboehr/phpstan-laravel-validation/blob/1fe0f3b4a5bddb3ae4df7d59025cd181caa1142a/src/Validation/TypeResolver.php#L158

I'm testing against a [dump from the laravel test suite](https://github.com/jbboehr/phpstan-laravel-validation/blob/26f81b65ad5ea2d48490a6b82a5c5b9fbcc09a24/tests/fixtures/laravel-export-v9.php) but that only catches too-specific types, not the other way around :)
