### ISSUE TITLE
Narrow types are not accepted

### ISSUE THREAD

**Issue by Daanra** [jbboehr/phpstan-laravel-validation#9]
Ran into a weird issue using this plugin. Not entirely sure whether it is actually caused by this library. When I attempt to run `collect()` on the value that resides in the request, I get an error that the array type is not accepted which makes zero sense to me.

```php
$x = $request->validate(['values.*' => 'required|integer'])['values'];
dumpType($x); // array<int|string, int|numeric-string> 
$t = collect($x); // Parameter #1 $value of function collect expects Illuminate\Contracts\Support\Arrayable<int|string, int|string>|iterable<int|string, int|string>|null, array<int|string, int|numeric-string> given.  
```

The weird thing is, the inferred type should be accepted. When I instantiate a new variable and explicitly give it this type, PHPStan returns no errors:
```php
/** @var array<int|string, int|numeric-string> $val */
$val = [1, '1'];
dumpType($val); // array<int|string, int|numeric-string>
collect($val); // No errors
```
I have no clue why the former code fragment displays and error but the latter does not. I figured there might be a small bug in the type inference. 

Using PHPStan level 9

**Comment by jbboehr** [comment]
That was a bit of a weird one. I guess `numeric-string` is represented internally as essentially `string & numeric-string`. Thanks for reporting it!
